{
 "title": "M3Coordinator Details",
 "tags": [ "disable-sync" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Reads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries Per Second (remote)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(coordinator_fetch_success{}[1m])",
     "legendFormat": "queries_per_second"
    }
   ]
  },
  {
   "title": "Query Errors Per Second (remote)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_fetch_errors{}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  { "title": "Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Remote Writes Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(coordinator_m3db_client_write_success{}[1m]))",
     "legendFormat": "write_per_second"
    }
   ]
  },
  {
   "title": "Remote Write Batch Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coordinator_write_success{}[1m]))",
     "legendFormat": "2XX"
    },
    {
     "expr": "sum(rate(coordinator_write_errors{}[1m])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Write Ingest Latency (Relative to datapoint timestamp)",
   "type": "graph",
   "description": "This is the measurement of the difference between the server's relative time now() and the datapoint's timestamp after it is persisted (or fails) to be written.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coordinator_ingest_latency_bucket[1m])) by (le))",
     "legendFormat": "p99 latency"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(coordinator_ingest_latency_bucket[1m])) by (le))",
     "legendFormat": "p95 latency"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(coordinator_ingest_latency_bucket[1m])) by (le))",
     "legendFormat": "p75 latency"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(coordinator_ingest_latency_bucket[1m])) by (le))",
     "legendFormat": "p50 latency"
    }
   ]
  }
 ]
}